services:
  ipcounter:
    build: .
    container_name: ipcounter
    ports:
      - 5000:5000
      - 9102:9102
    restart: always
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    ports:
      - 9090:9090
    restart: always
    user: "0"
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./prometheus_data:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:11.5.1
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
